### ISSUE TITLE
wrong package.json

### ISSUE THREAD

**Issue by fanatid** [bitcoinjs/bip66#1]
some fields refer to [bip69](https://github.com/bitcoinjs/bip69)
https://github.com/bitcoinjs/bip66/blob/master/package.json#L9
https://github.com/bitcoinjs/bip66/blob/master/package.json#L12
https://github.com/bitcoinjs/bip66/blob/master/package.json#L14

**Comment by dcousens** [comment]
Cheers @fanatid

**Comment by fanatid** [comment]
@dcousens can you publish this? :)
