### ISSUE TITLE
Accord bip66, lenR check bug

### ISSUE THREAD

**Issue by guotie** [bitcoinjs/bip66#11]
```
if (5 + lenR >= buffer.length) return false
```

should be 

```
if (5 + lenR > buffer.length) return false
```

because buffer is slice the last byte.

https://github.com/bitcoin/bips/blob/master/bip-0066.mediawiki: 

```
    // Make sure the length of the S element is still inside the signature.
    if (5 + lenR >= sig.size()) return false;
```

**Comment by dcousens** [comment]
@guotie can you provide a test fixture?

**Comment by dcousens** [comment]
> because buffer is slice the last byte.

What `buffer.slice`?

**Comment by guotie** [comment]
I mean the input param buffer length  =  origin buffer length - 1, so the condition should be change accord the code :

```
    // Make sure the length of the S element is still inside the signature.
    if (5 + lenR >= sig.size()) return false;
```

**Comment by dcousens** [comment]
@guotie `buffer length = origin buffer length - 1` what?
Can you directly link to the code you are querying?

**Comment by guotie** [comment]
line 16

**Comment by dcousens** [comment]
@guotie I have no idea what you are referring to.

There is no `buffer.length - 1`.
There is no `buffer.slice`.

If you could provide a test case that shows clearly what isn't working, I'll re-open this issue,  but as is,  the code appears to be OK.

I don't doubt you might be on to something,  but, I can't see based on the hints you are providing :confused: .

**Comment by guotie** [comment]
https://github.com/bitcoin/bips/blob/master/bip-0066.mediawiki#der-encoding-reference

![u sor ohb47w65a vpf2r 6](https://user-images.githubusercontent.com/42231/41583956-941516a0-73d8-11e8-8f74-f8c243f3eb3b.png)


![ye 6 r q5 18ktl vc4 7](https://user-images.githubusercontent.com/42231/41583974-a31db986-73d8-11e8-9f53-b10457674eac.png)

**Comment by dcousens** [comment]
Are you saying it should be `4 + lenR`?

**Comment by guotie** [comment]
i think so, should it ?

**Comment by guotie** [comment]
yes, I think so

**Comment by dcousens** [comment]
See https://github.com/bitcoinjs/bip66/pull/12 for working PR,  tests needed though
