### ISSUE TITLE
Fails to encode 300602010002010001

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bip66#6]
This is part of the canonical bitcoin test suite,  and this module now fails since the latest patch.

> Error: R value excessively padded

**Comment by dcousens** [comment]
ping @fanatid,  might need to revert your changes to `encode`

**Comment by fanatid** [comment]
@dcousens `decode` wasn't changed

``` js
> bip66.decode(new Buffer('300602010002010001', 'hex'))
Error: DER sequence length is invalid
```
